### ISSUE TITLE
Implement a Handler which is not Serializable

### ISSUE THREAD

**Issue by memedidou** [audit4j/audit4j-core#12]
Hi,

I'm implementing my own Handler but I'm unable start my service anymore due to this exception 

```
Caused by: org.audit4j.core.exception.InitializationException: initialization failed.!!
  at org.audit4j.core.Context.init(Context.java:122)
  at org.audit4j.core.AuditManager.init(AuditManager.java:53)
  at org.audit4j.core.AuditManager.getInstance(AuditManager.java:118)
  at org.audit4j.core.AuditManager.startWithConfiguration(AuditManager.java:176)
  at org.audit4j.integration.spring.SpringAudit4jConfig.afterPropertiesSet(SpringAudit4jConfig.java:69)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
  ... 40 more
Caused by: org.audit4j.core.exception.ValidationException: Handler implementation(...RepositoryHandler) shuold be a serializable type.
  at org.audit4j.core.ValidationManager.validateConfigurations(ValidationManager.java:86)
  at org.audit4j.core.Context.init(Context.java:119)
  ... 46 more
```

Is it possible to avoid the need of being a `Serializable` object, or is something mandatory ? My handler uses/implements other objects and interfaces that are not serializable.

Thanks.

**Comment by janithb** [comment]
Fixed issue in audit4j-core-2.4.0-alpha3.
