### ISSUE TITLE
Errors after running Application

### ISSUE THREAD

**Issue by Tamarick** [audit4j/audit4j-core#69]
I have implemented Audit4j with Spring boot in my application. The application starts up but once I try to reach a page on the server (tomcat), I am hit with many error messages. Below are a few. I ran the sample project and that works fine, but implementing it in a larger project causes a lot of errors.
Any solutions for this?

	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:148)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	... 47 more
Caused by: org.audit4j.core.exception.Audit4jRuntimeException: Error due to converting object to string representation. 
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:148)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:106)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
Audit4j:ERROR Problem while running Audit4j: Error due to converting object to string representation. 
org.audit4j.core.exception.Audit4jRuntimeException: Error due to converting object to string representation. 
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:148)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:87)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.serialize(ObjectToFieldsSerializer.java:166)
	at org.audit4j.core.DefaultAnnotationTransformer.getFields(DefaultAnnotationTransformer.java:159)
	at org.audit4j.core.DefaultAnnotationTransformer.transformToEvent(DefaultAnnotationTransformer.java:96)
	at org.audit4j.core.io.AsyncAnnotationAuditOutputStream$1.accept(AsyncAnnotationAuditOutputStream.java:71)
	at org.audit4j.core.io.AsyncAnnotationAuditOutputStream$1.accept(AsyncAnnotationAuditOutputStream.java:68)
	at reactor.function.support.Boundary$1.accept(Boundary.java:67)
	at reactor.core.action.CallbackAction.doAccept(CallbackAction.java:36)
	at reactor.core.action.Action.accept(Action.java:52)
	at reactor.core.action.Action.accept(Action.java:32)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:73)
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:78)
	at reactor.event.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:64)
	at reactor.event.dispatch.AbstractSingleThreadDispatcher$SingleThreadTask.run(AbstractSingleThreadDispatcher.java:50)
	at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:115)
	at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:112)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Audit4j:ERROR Problem while running Audit4j: Error due to converting object to string representation. 
org.audit4j.core.exception.Audit4jRuntimeException: Error due to converting object to string representation. 
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:148)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:87)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	at org.audit4j.core.ObjectToFieldsSerializer.serialize(ObjectToFieldsSerializer.java:166)
	at org.audit4j.core.DefaultAnnotationTransformer.getFields(DefaultAnnotationTransformer.java:159)
	at org.audit4j.core.DefaultAnnotationTransformer.transformToEvent(DefaultAnnotationTransformer.java:96)
	at org.audit4j.core.io.AsyncAnnotationAuditOutputStream$1.accept(AsyncAnnotationAuditOutputStream.java:71)
	at org.audit4j.core.io.AsyncAnnotationAuditOutputStream$1.accept(AsyncAnnotationAuditOutputStream.java:68)
	at reactor.function.support.Boundary$1.accept(Boundary.java:67)
	at reactor.core.action.CallbackAction.doAccept(CallbackAction.java:36)
	at reactor.core.action.Action.accept(Action.java:52)
	at reactor.core.action.Action.accept(Action.java:32)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:73)
	at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:78)
	at reactor.event.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:64)
	at reactor.event.dispatch.AbstractSingleThreadDispatcher$SingleThreadTask.run(AbstractSingleThreadDispatcher.java:50)
	at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:115)
	at reactor.event.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:112)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at sun.security.util.DerValue.equals(DerValue.java:799)
	at sun.security.x509.AlgorithmId.equals(AlgorithmId.java:266)
	at sun.security.x509.AlgorithmId.equals(AlgorithmId.java:282)
	at java.util.ArrayList.indexOf(ArrayList.java:321)
	at java.util.ArrayList.contains(ArrayList.java:304)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:62)
	at org.audit4j.core.ObjectToFieldsSerializer.toFields(ObjectToFieldsSerializer.java:138)
	... 53 more

**Comment by franck-benault** [comment]
Could you please give an example of simple method in error ?

or does the issue occurs only when there is big charge on the server ?

Regards Franck

**Comment by Tamarick** [comment]
Big charge on the server. I used a @Audit annotation for a method that calls a api for a home page.

@Audit
	@RequestMapping("/home")
	public String login(

**Comment by Tamarick** [comment]
Hi Rajesh,

I didn’t fix the error or found any work around this issue.

Regards,
Tamarick

**Comment by rajeshvalsala** [comment]
Hi Tamarick,

I fixed this by using @IgnoreAudit annotation for HttpServletRequest object.

Thanks.

**Comment by pvitor** [comment]
I passing for this, and verified wish list not passing the type of the list and generate the error. Hibernate not mapping list with relation 1 to n.

Thanks.

**Comment by scintilla932** [comment]
Hi, Anyone found any solution to this? @pvitor  could you please elaborate your case a bit. I am facing the same issue.
